name: CI ms-backend

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: 17

      - name: Execute Maven build
        run: mvn clean package -Dmaven.test.skip=true

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: trebor006
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: trebor006/ms-segip-simulation:latest

      - name: Pull image from Docker Hub
        run: docker pull trebor006/ms-segip-simulation:latest

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Tag image
        run:
          docker tag trebor006/ms-segip-simulation:latest registry.digitalocean.com/denuncity-registry/ms-segip-simulation:1.0.0
      - name: Push image to DO Container Registry
        run: docker push registry.digitalocean.com/denuncity-registry/ms-segip-simulation:1.0.0

#      - name: Clean up old images
#        run: echo "y" | doctl registry repository delete-manifests denuncity-registry/ms-segip-simulation --keep 1

